### PR TITLE
Allow user-specified reasonFilter for retrieving builds

### PR DESCRIPTION
**Pull request by coloursofnoise**
Adds a `reasonFilter` parameter that allows for filtering builds by the provided reason.
ex: allow actions to download builds from pipelines that have both main and PR builds, and only retrieve artifacts from the appropriate build type.

Can be used to specify any of the reason described in the [Azure Devops Documentation](https://docs.microsoft.com/en-us/rest/api/azure/devops/build/builds/list?view=azure-devops-rest-6.0#buildreason).

### CODE REVIEW

**Comment by dscho** [comment]
Thank you for working on this!

I have just one issue with this: it might be too free-form to be helpful for the users. It might make more sense to offer specific settings for e.g. `failed` or whatever _your_ particular use case is.

Speaking of which: what _is_ your use case?

**Comment by coloursofnoise** [comment]
My specific use-case is the `reasonFilter` parameter, our pipeline runs for main repo CI as well as PRs, and the particular artifact I need isn't built for PRs.
More accurately I want the latest build that has the particular artifact available, but in this case that *should* always be the same as `&statusFilter=completed&resultFilter=succeeded&reasonFilter=individualCI`.

**Comment by dscho** [comment]
> 
> 
> My specific use-case is the `reasonFilter` parameter, our pipeline runs for main repo CI as well as PRs, and the particular artifact I need isn't built for PRs.
> More accurately I want the latest build that has the particular artifact available, but in this case that _should_ always be the same as `&statusFilter=completed&resultFilter=succeeded&reasonFilter=individualCI`.

Oh, that's a really good idea! How about adding an optional setting `reasonFilter`, which, when set, will be appended as `&reasonFilter=${reasonFilter}` (after sanitizing/validating the input)? That way, not only are we able to adapt this in the future if the Azure DevOps API should change, but it is also eminently more discoverable/usable a feature for users.

**Comment by coloursofnoise** [comment]
Sure thing, do you want that in a new PR or should I just edit this one?
I can also add a few more of the available filters that could be useful if you think that's appropriate.

**Comment by dscho** [comment]
> 
> 
> Sure thing, do you want that in a new PR or should I just edit this one?
> I can also add a few more of the available filters that could be useful if you think that's appropriate.

Oh, please just edit this one!

**Comment by coloursofnoise** [comment]
@dscho these changes seem to work fine for my test build

**Comment by coloursofnoise** [comment]
@dscho what needs to be done for this to be merged?
I noticed that the test has failed, but I'm not sure what to do to make them succeed.

**Comment by dscho** [comment]
> @dscho what needs to be done for this to be merged?

It was a bit tricky, I seemed to have trouble getting the exact shape of the `index.js.map` file locally as the workflow run. So I force-pushed a version that was generated by the run, and then merged.

[The marketplace entry](https://github.com/marketplace/actions/download-an-artifact-from-an-azure-pipeline) shows the correct version, therefore I believe that this is now officially resolved! Thank you so much for your contribution!

**Pull request merged**
